version: '3.8'

services:

  backend:
    image: ghcr.io/xyhelper/xyucenter
    ports:
      - "8600:8001"
    environment:
      - TZ=Asia/Shanghai
      - AUTH0_DOMAIN= #Auth0 域名
      - AUTH0_CLIENT_ID= # Auth0 客户端ID
      - AUTH0_CLIENT_SECRET= #Auth0 客户端密钥
      - AUTH0_CALLBACK_URL= # 本服务地址
      - BILL_COMPANY_NAME=  # 账单中的公司名称
      - BILL_COMPANY_ADDRESS= # 账单中的公司地址
      - JWT_SECRET_KEY= #jwt密钥
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./manifest:/app/manifest
      - ./certs:/app/certs # 支付证书路径
      - ./config/config.yaml:/app/config.yaml
    restart: unless-stopped

  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "cool"
      MYSQL_USER: "cool"
      MYSQL_PASSWORD: "123123"
    restart: unless-stopped

  redis:
    image: redis
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/:/data/
    restart: unless-stopped